name: PvPTower
version: ${project.version}
main: incrafty.maks.Main
api-version: 1.16
commands:
  struct:
    description: generation du struct
  start:
    description: lancement de la parti
  myteam:
    description: gets your team
  assign:
    description: Assigns players to teams